# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myo_emg.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 270))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 1, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_2.sizePolicy().hasHeightForWidth())
        self.listWidget_2.setSizePolicy(sizePolicy)
        self.listWidget_2.setMaximumSize(QtCore.QSize(73, 16777215))
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout.addWidget(self.listWidget_2, 1, 3, 2, 1)
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        self.mdiArea.setMinimumSize(QtCore.QSize(330, 0))
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout.addWidget(self.mdiArea, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.mdiArea_2 = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea_2.setObjectName("mdiArea_2")
        self.gridLayout.addWidget(self.mdiArea_2, 2, 2, 1, 1)
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setObjectName("treeView")
        self.gridLayout.addWidget(self.treeView, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName("menubar")
        self.menuDevice = QtWidgets.QMenu(self.menubar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuDevice.sizePolicy().hasHeightForWidth())
        self.menuDevice.setSizePolicy(sizePolicy)
        self.menuDevice.setObjectName("menuDevice")
        self.menuCapture = QtWidgets.QMenu(self.menubar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuCapture.sizePolicy().hasHeightForWidth())
        self.menuCapture.setSizePolicy(sizePolicy)
        self.menuCapture.setObjectName("menuCapture")
        self.menuCapture_SEMG = QtWidgets.QMenu(self.menuCapture)
        self.menuCapture_SEMG.setObjectName("menuCapture_SEMG")
        self.menuSession = QtWidgets.QMenu(self.menubar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuSession.sizePolicy().hasHeightForWidth())
        self.menuSession.setSizePolicy(sizePolicy)
        self.menuSession.setObjectName("menuSession")
        self.menuProfile = QtWidgets.QMenu(self.menubar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuProfile.sizePolicy().hasHeightForWidth())
        self.menuProfile.setSizePolicy(sizePolicy)
        self.menuProfile.setObjectName("menuProfile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMyo = QtWidgets.QAction(MainWindow)
        self.actionMyo.setObjectName("actionMyo")
        self.actionCamera = QtWidgets.QAction(MainWindow)
        self.actionCamera.setObjectName("actionCamera")
        self.actionCapture_IMU = QtWidgets.QAction(MainWindow)
        self.actionCapture_IMU.setObjectName("actionCapture_IMU")
        self.actionStart_Capture = QtWidgets.QAction(MainWindow)
        self.actionStart_Capture.setObjectName("actionStart_Capture")
        self.actionStop_Capture = QtWidgets.QAction(MainWindow)
        self.actionStop_Capture.setObjectName("actionStop_Capture")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_Profile = QtWidgets.QAction(MainWindow)
        self.actionSave_Profile.setObjectName("actionSave_Profile")
        self.actionLoad_Profile = QtWidgets.QAction(MainWindow)
        self.actionLoad_Profile.setObjectName("actionLoad_Profile")
        self.menuDevice.addAction(self.actionMyo)
        self.menuDevice.addAction(self.actionCamera)
        self.menuCapture.addAction(self.menuCapture_SEMG.menuAction())
        self.menuCapture.addAction(self.actionCapture_IMU)
        self.menuSession.addAction(self.actionStart_Capture)
        self.menuSession.addAction(self.actionStop_Capture)
        self.menuSession.addAction(self.actionSave)
        self.menuProfile.addAction(self.actionSave_Profile)
        self.menuProfile.addAction(self.actionLoad_Profile)
        self.menubar.addAction(self.menuDevice.menuAction())
        self.menubar.addAction(self.menuCapture.menuAction())
        self.menubar.addAction(self.menuSession.menuAction())
        self.menubar.addAction(self.menuProfile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MyoSEMG"))
        self.menuDevice.setTitle(_translate("MainWindow", "Device"))
        self.menuCapture.setTitle(_translate("MainWindow", "Capture"))
        self.menuCapture_SEMG.setTitle(_translate("MainWindow", "Capture SEMG"))
        self.menuSession.setTitle(_translate("MainWindow", "Session"))
        self.menuProfile.setTitle(_translate("MainWindow", "Profile"))
        self.actionMyo.setText(_translate("MainWindow", "Myo"))
        self.actionCamera.setText(_translate("MainWindow", "Camera"))
        self.actionCapture_IMU.setText(_translate("MainWindow", "Capture IMU"))
        self.actionStart_Capture.setText(_translate("MainWindow", "Start Capture"))
        self.actionStop_Capture.setText(_translate("MainWindow", "Stop Capture"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_Profile.setText(_translate("MainWindow", "Save Profile"))
        self.actionLoad_Profile.setText(_translate("MainWindow", "Load Profile"))

import myo_emg_rc
